# Example of Job Routes that site admins can specify in site level config file
# job_routes:
#  - [
#        TargetUniverse = 5;\n
#        Name = "Custom Job Route 1 ";\n
#        Requirements = ( Owner =?= local_user_1 );
#        set_AccountingGroup("local");
#    ]
#  - [
#        TargetUniverse = 5;\n
#        Name = "Custom Job Route 2 ";\n
#        Requirements = ( Owner =?= local_user_2 );
#    ]
#
# Example for site admins to specify additional
# condor_mapfile_entries:
#    - 'GSI "^<DISTINGUISHED NAME>$" <USERNAME>'
expected-from-site-level-config:
  condor_host_execution_id: { type: int(), required: true, use_default: false, description: "The execution id of the HTCondor-Batch lightweight component in the site level config file."}
  uid_domain: {type: str(), required: true, use_default: true, description: "The UID_DOMAIN macro is used to decide under which user to run jobs. If the $(UID_DOMAIN) on the submitting machine is different than the $(UID_DOMAIN) on the machine that runs a job, then HTCondor runs the job as the user nobody"}
  user_accounts: {type: list(str()), required: false, use_default: false, description: "A list of user accounts that should be created in the container. If these accounts are used in the condor_mapfile, then please also specify them in the config section of the HTCondor-Worker component repository"}
  condor_mapfile_entries: {type: list(), required: false, use_default: false, description: "A list of lines inserted at the top of the condor_mapfile. The users would be automatically created by the SIMPLE framework."}
  job_routes: {type: list(), required: false, use_default: false, description: "A list of additional routes for the HTCondor JobRouter that take priority over the autogenerated job routes. See the config-schema.yaml file in the HTCondor-CE repository for SIMPLE framework on GitHub for an example"}
  gss_assist_gridmap_cache_expiration: {type: int(), required: true, use_default: true, description: "The length of time, in seconds, to cache the result of the Globus mapping lookup result when using Globus to map certificates to HTCondor user names. The lookup only occurs when the canonical name GSS_ASSIST_GRIDMAP is present in the HTCondor map file. The default value is 0 seconds, which is a special value that disables caching. The cache uses the DN and VOMS FQAN as a key; very rare Globus configurations that utilize other certificate attributes for the mapping may cause the cache to return a different user than Globus."}
  per_job_history_dir: {type: str(), required: true, use_default: true, description: "If set to a directory writable by the HTCondor user, when a job leaves the condor_schedd's queue, a copy of the job's ClassAd will be written in that directory. The files are named history, with the job's cluster and process number appended."}